[project]
name = "sentinelops"
version = "0.1.0"
description = "Autonomous Bug Triage & Fix Agent"
requires-python = ">=3.11"
dependencies = [
    "fastapi",
    "uvicorn",
    "pydantic",
    "pydantic-settings",
    "python-multipart",
    "httpx",
    "langgraph",
    "langchain-ollama",
    "ollama",
    "mcp",
    "langchain-mcp-adapters",
    "psycopg2-binary",
    "pgvector",
    "sqlalchemy",
    "tenacity",
    "asyncpg"
]

[project.optional-dependencies]
test = ["pytest"]